#!/usr/bin/env node
/**
 * Interactive setup — prompts for each API key one by one and saves them to
 * .env.local so the app runs on any machine.
 *
 *   npm run setup
 *
 * Re-running it updates existing values (your previous answer is shown as the
 * default — just press Enter to keep it).
 */
import { createInterface } from 'node:readline';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ENV_PATH = process.env.SETUP_ENV_PATH || join(ROOT, '.env.local');

// Fields we ask for. `secret` masks nothing fancy but flags sensitivity.
const FIELDS = [
  {
    key: 'ALPHA_API_KEY',
    label: 'Alpha Arcade API key',
    hint: 'from alphaarcade.com — starts with aa_pk_',
    default: 'aa_pk_nlT1GPERtPX_mlBgh2QXGBGe9qfbz70CNVamCruVAgg',
  },
  {
    key: 'OPENROUTER_API_KEY',
    label: 'OpenRouter API key (fake-news / credibility LLM)',
    hint: 'from openrouter.ai — starts with sk-or-',
    default: '',
  },
  {
    key: 'X402_RECIPIENT_ADDRESS',
    label: 'Algorand address that receives x402 payments',
    hint: '58-char Algorand address',
    default: 'EW5HE3PN3K62CXZKPJPDLWV7REAKYESNVYDHQKJTD276BAU7BW6VXP777I',
  },
  {
    key: 'USDC_TESTNET_ASSET_ID',
    label: 'USDC testnet asset ID',
    hint: 'Algorand testnet USDC = 10458941',
    default: '10458941',
  },
  {
    key: 'BYPASS_X402',
    label: 'Bypass on-chain payment verification? (true = demo mode)',
    hint: 'true for demo/judging, false to require real signed payments',
    default: 'true',
  },
];

// Static keys that don't need prompting but should exist.
const STATIC = {
  ALPHA_API_BASE_URL: 'https://platform.alphaarcade.com/api',
  LLM_MODEL: 'google/gemini-2.0-flash-001',
  ALGOD_SERVER: 'https://testnet-api.algonode.cloud',
  ALGOD_PORT: '443',
  ALGOD_INDEXER_SERVER: 'https://testnet-idx.algonode.cloud',
  BINANCE_API_BASE: 'https://api.binance.com',
  DATABASE_URL: 'file:./dev.db',
};

function parseEnv(text) {
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const eq = t.indexOf('=');
    if (eq === -1) continue;
    out[t.slice(0, eq).trim()] = t.slice(eq + 1).trim();
  }
  return out;
}

async function main() {
  const existing = existsSync(ENV_PATH) ? parseEnv(readFileSync(ENV_PATH, 'utf8')) : {};

  const rl = createInterface({ input: process.stdin, output: process.stdout });
  let closed = false;
  let pending = null; // resolver for an in-flight question
  rl.on('close', () => {
    closed = true;
    if (pending) { const r = pending; pending = null; r(''); }
  });
  // Resolve to '' if stdin hits EOF (e.g. piped/non-interactive) so we never hang.
  const ask = (q) =>
    new Promise((res) => {
      if (closed) { process.stdout.write(q + '\n'); return res(''); }
      pending = res;
      rl.question(q, (a) => { pending = null; res(a.trim()); });
    });

  console.log('\n╔══════════════════════════════════════════════════════╗');
  console.log('║   CorrFarm setup — enter your API keys (Enter=keep)   ║');
  console.log('╚══════════════════════════════════════════════════════╝\n');

  const values = {};
  for (const f of FIELDS) {
    const current = existing[f.key] || f.default || '';
    const shown = current
      ? (f.key.includes('KEY') && current.length > 12
          ? current.slice(0, 8) + '…' + current.slice(-4)
          : current)
      : '(none)';
    console.log(`• ${f.label}`);
    console.log(`  ${f.hint}`);
    const answer = await ask(`  [${shown}] > `);
    values[f.key] = answer || current;
    console.log('');
  }

  rl.close();

  // Merge: keep any other pre-existing keys, apply statics if absent.
  const merged = { ...STATIC, ...existing, ...values };

  const lines = [
    '# Generated by `npm run setup` — safe to edit by hand',
    '',
    '# ── API keys ──',
    `ALPHA_API_KEY=${merged.ALPHA_API_KEY || ''}`,
    `ALPHA_API_BASE_URL=${merged.ALPHA_API_BASE_URL}`,
    `OPENROUTER_API_KEY=${merged.OPENROUTER_API_KEY || ''}`,
    `LLM_MODEL=${merged.LLM_MODEL}`,
    '',
    '# ── Algorand / x402 ──',
    `X402_RECIPIENT_ADDRESS=${merged.X402_RECIPIENT_ADDRESS || ''}`,
    `USDC_TESTNET_ASSET_ID=${merged.USDC_TESTNET_ASSET_ID}`,
    `BYPASS_X402=${merged.BYPASS_X402}`,
    // Preserve agent wallet keys if already set
    ...(merged.X402_AGENT_ADDRESS ? [
      '# x402 agent wallet — auto-pays on-chain (fund via https://lora.algokit.io/testnet)',
      `X402_AGENT_ADDRESS=${merged.X402_AGENT_ADDRESS}`,
      `X402_AGENT_MNEMONIC=${merged.X402_AGENT_MNEMONIC || ''}`,
      `X402_ALGO_AMOUNT=${merged.X402_ALGO_AMOUNT || '50000'}`,
    ] : []),
    `ALGOD_SERVER=${merged.ALGOD_SERVER}`,
    `ALGOD_PORT=${merged.ALGOD_PORT}`,
    `ALGOD_INDEXER_SERVER=${merged.ALGOD_INDEXER_SERVER}`,
    '',
    '# ── Misc ──',
    `BINANCE_API_BASE=${merged.BINANCE_API_BASE}`,
    `DATABASE_URL=${merged.DATABASE_URL}`,
    '',
  ];

  writeFileSync(ENV_PATH, lines.join('\n'), 'utf8');

  const agentAddr = merged.X402_AGENT_ADDRESS;
  console.log('✅ Saved to .env.local');
  if (agentAddr) {
    console.log('\n💳 Agent wallet (x402 real payments):');
    console.log(`   Address: ${agentAddr}`);
    console.log(`   Fund at: https://lora.algokit.io/testnet?account=${agentAddr}`);
    console.log('   (Without funding, demo mode will be used automatically)');
  }
  console.log('\n   Start the app with:  npm run dev');
  console.log('   Then open:           http://localhost:3000\n');
}

main().catch((e) => {
  console.error('Setup failed:', e);
  process.exit(1);
});
